package com.roche.ssg.buildsrc

object Versions {
    const val gradlePlugin = "4.2.1"
    const val buildInfoExtractorGradle = "4.21.0"
    const val kotlin = "1.5.30"
    const val appCompat = "1.2.0"
    const val material = "1.2.1"
    const val constraintLayout = "2.0.4"
    const val junit = "4.13.2"
    const val androidXJunit = "1.1.2"
    const val navigation = "2.3.3"
    const val coreKtx = "1.3.2"
    const val androidxJunit = "1.1.3"
    const val espressoCore = "3.3.0"
    const val recyclerviewSelection = "1.1.0"
    const val work = "2.7.1"
    const val dokkaGradlePlugin = "1.4.20"
    const val firebaseAppDistributionGradle = "2.1.3"
    const val gms = "4.3.10"
    const val jacoco = "0.8.7"
    const val hilt = "2.38.1"
    const val coroutines = "1.3.9"
    const val lifecycle = "2.2.0"
    const val activityVersion = "1.2.3"
    const val splitVersion = "2.7.2"
    const val gsonVersion = "2.8.8"
    const val ktorVersion = "1.6.3"
    const val firebase = "28.4.2"
    const val amplify = "1.28.1"
    const val amplitudeAndroidSdk = "2.34.1"
    const val okhttp = "4.9.1"
    const val amplitudeExperimentAndroidClient = "1.3.0"
    const val legacySupportV4 = "1.0.0"
    const val biometric = "1.2.0-alpha03"
    const val securityCrypto = "1.1.0-alpha02"
    const val uiAutomator = "2.2.0"
    const val testRules = "1.0.2"
    const val espressoContrib = "2.2.2"
    const val testCore = "1.4.0"
    const val coreTesting = "2.1.0"
    const val mockitoCore = "2.19.0"
    const val mockk = "1.12.0"
    const val retrofit = "2.9.0"
    const val activityKtx = "1.2.3"
    const val javaxInject = "1"
    const val kotlinxCoroutinesCore = "1.5.1"
    const val json ="20210307"
    const val localBroadcastManager = "1.0.0"

    object RocheCommonComponent {
        const val utils = "1.0.2"
    }

}