image:
  name: bitbucketpipelines/android-ci-image

definitions:
  steps:
  - step: &build
      name: Build
      caches:
        - gradle
      script:
        - cd RocheCommonSDK
        - ./gradlew assembleDebug

  - step: &unittest
      name: Unit Tests
      caches:
        - gradle
      script:
        - cd RocheCommonSDK
        - ./gradlew test

pipelines:
  branches:
    bitbucket-pipeline-ci:
      - step: *build
      - step: *unittest