image:
  name: 651863433406.dkr.ecr.us-east-2.amazonaws.com/dev/dhp-base-android-builder:build-6
  aws:
    access-key: $ECR_READONLY_KEY_ID
    secret-key: $ECR_READONLY_SECRET_KEY

definitions:
  steps:
  - step: &build
      name: Build
      caches:
        - gradle
        - android-sdk
      script:
        - cd RocheCommonSDK
        - chmod a+x ./gradlew
        - ./gradlew assembleDebug

  - step: &unittest
      name: Unit Tests
      caches:
        - gradle
        - android-sdk
      script:
        - cd RocheCommonSDK
        - ./gradlew test

  - step: &whitesource
      name: Whitesource
      caches:
        - gradle
      script:
        - pipe: WhitesourceSoftware/whitesource-scan:1.3.0
          variables:
            API_KEY: $WHITESOURCE_API_KEY
            DIRECTORY: 'RocheCommonSDK'
            CONFIG_FILE_PATH: './RocheCommonSDK/wss-unified-agent.config'

pipelines:
  branches:
    bitbucket-pipeline-ci:
      - step: *build
      - parallel:
          - step: *unittest
          - step: *whitesource

definitions:
    caches:
      android-sdk: android-sdk