image:
  name: 651863433406.dkr.ecr.us-east-2.amazonaws.com/dev/dhp-base-android-builder:build-6
  run-as-user: 1000
  aws:
    access-key: $ECR_READONLY_KEY_ID
    secret-key: $ECR_READONLY_SECRET_KEY

definitions:
  steps:
  - step: &build
      name: Build
      caches:
        - gradle
        - android-sdk
      script:
        - cd RocheCommonSDK
        - chmod a+x ./gradlew
        - ./gradlew assembleDebug

  - step: &unittest
      name: Unit Tests
      caches:
        - gradle
        - android-sdk
      script:
        - cd RocheCommonSDK
        - ./gradlew test

pipelines:
  branches:
    bitbucket-pipeline-ci:
      - step: *build

definitions:
    caches:
      android-sdk: android-sdk