image: java:8

definitions:
  steps:
  - step: &build
      name: Build
      caches:
        - gradle
        - android-sdk
      script:
        # Download and unzip android sdk
        - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
        - unzip -o -qq android-sdk.zip -d android-sdk

        # Define Android Home and add PATHs
        - export ANDROID_HOME="/opt/atlassian/pipelines/agent/build/android-sdk"
        - export PATH="$ANDROID_HOME/cmdline-tools/bin:$PATH"

        # Download packages.
        - yes | sdkmanager "platform-tools"
        - yes | sdkmanager "platforms;android-29"
        - yes | sdkmanager "build-tools;29.0.2"
        - yes | sdkmanager "extras;android;m2repository"
        - yes | sdkmanager "extras;google;m2repository"
        - yes | sdkmanager "extras;google;instantapps"
        - yes | sdkmanager --licenses

        - cd RocheCommonSDK
        - chmod a+x ./gradlew
        - ./gradlew assembleDebug

  - step: &unittest
      name: Unit Tests
      caches:
        - gradle
      script:
        - cd RocheCommonSDK
        - ./gradlew test

pipelines:
  branches:
    bitbucket-pipeline-ci:
      - step: *build

definitions:
    caches:
      android-sdk: android-sdk